### ISSUE TITLE
Allow to attach a docker-selenium container

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov-nodejs#6]
if `.shoov.yml` has

```yml
addons:
  - selenium
```

We could attach a [docker-selenium](https://github.com/elgalu/docker-selenium) container, and open a port -- so the docker [php-ci](https://github.com/shoov/php-ci) can use it

**Comment by solker** [comment]
I have successfully ran CI Build docker with Silenium docker. To do this your dockers should have specific names. Really specific name should have only docker with silenium because CI Build docker should know name of Silenium server.

After need to update behat/behat.config.local.example file and change silenium wd-host property to `http://silenium:4470/wd/hub`. silenium url it's a alias for docker silenium ip. And push it to github.

First need to run silenium. After silenium started we can run our ci-build and it's will connect to silenium and do job. After finish we need remove all containers. (Or silenium can work forever?) 

Next part is change NodeJS settings to work with silenium.

**Comment by amitaibu** [comment]
> (Or silenium can work forever?)

No, container per task

> Also here is problem with names,

The build ID is unique, so you can have `selenium-[build ID]` and `main-[build ID]`

**Comment by amitaibu** [comment]
Problem is how would you deal with multiple containers in the same time - the ports should be bindable only to the PHP-CI container

**Comment by solker** [comment]
@amitaibu it's not a problem we don't need forward ports outside.
